/* Autogenerated by MaKL - Sun Dec 13 10:22:55 GMT 2009 */
/* Configure arguments:  */

#ifndef _KLAPP_CONF_H_
#define _KLAPP_CONF_H_

#undef KLAPP_VERSION
#define KLAPP_VERSION "2.2.1"

#undef DESTDIR
#define DESTDIR "/usr/local"

#undef BINDIR
#define BINDIR "/usr/local/bin"

#undef SBINDIR
#define SBINDIR "/usr/local/sbin"

#undef CONFDIR
#define CONFDIR "/usr/local/etc"

#undef INCDIR
#define INCDIR "/usr/local/include"

#undef LIBDIR
#define LIBDIR "/usr/local/lib"

#undef SHLIBDIR
#define SHLIBDIR "/usr/local/lib"

#undef LIBEXDIR
#define LIBEXDIR "/usr/local/libexec"

#undef VARDIR
#define VARDIR "/usr/local/var"

#undef SHAREDIR
#define SHAREDIR "/usr/local/share"

#undef MANDIR
#define MANDIR "/usr/local/share/man"

#undef DOCDIR
#define DOCDIR "/usr/local/share/doc"

#endif /* !_KLAPP_CONF_H_ */
