### Autogenerated file, don't edit. ###

# This file is not used by KLone, it's created to export some 
# variables to other makefiles

KLONE_VERSION=2.2.1
KLONE_DIR=/home/brett/livebox/trunk/userapps/hah/klone/klone-2.2.1
KLONE_SRC=/home/brett/livebox/trunk/userapps/hah/klone/klone-2.2.1/build/target/klone-core-2.2.1
KLONE_CFLAGS=-I/home/brett/livebox/trunk/userapps/hah/klone/klone-2.2.1/build/target/klone-core-2.2.1 -I/home/brett/livebox/trunk/userapps/hah/klone/klone-2.2.1/build/target/klone-core-2.2.1/libu/include
WEBAPP_DIR=/home/brett/livebox/trunk/userapps/hah/klone/webapp

