all:
	install -d $(INSTALL_DIR)/usr/share/flash
	install -m 444 *.swf $(INSTALL_DIR)/usr/share/flash
	install -m 444 *.png $(INSTALL_DIR)/usr/share/flash
	install -m 444 *.jpg $(INSTALL_DIR)/usr/share/flash
	install -m 444 *.xml $(INSTALL_DIR)/usr/share/flash

clean:
	echo "Nothing to clean"
