#!/usr/bin/lua
-- $Id$
lapp = require("pl.lapp")
local args = lapp
[[
  Various flags and option types
      <alias> (string)       Alias command
]]
require("xap")

local cmd = string.format([[
xap-header
{
class=alias
}
command
{
text=%s
}]],args.alias)

xap.init("dbzoo.lua.aliasmsg","FF00DF00")
xap.sendShort(cmd)
