#!/usr/bin/lua
-- $Id$
lapp = require("pl.lapp")
config = require("pl.config")
local args = lapp
[[
  Various flags and option types
      <alias> (string)       Alias command
]]
require("xap")

local cmd = string.format([[
xap-header
{
class=alias
}
command
{
text=%s
}]],args.alias)

local ini = config.read("/etc/xap-livebox.ini")
local instance = nil

if ini['xap'] then
   instance = ini.xap['instance']
   if instance then instance = instance.."." end
end
if instance == nil then instance="" end

xap.init("dbzoo.livebox."..instance.."aliasmsg","FF00DF00")
xap.sendShort(cmd)
