#!/usr/bin/lua
-- $Id$
-- Allow xAPBSC.cmd messages to be sent from the command line
-- also useful within a crontab 

lapp = require("pl.lapp")
config = require("pl.config")

lapp.add_type("onoff","string",
	function(x)
		if x ~= "on" and x ~= "off" then
			lapp.error("State can only be on or off")
		end
	end
	)

local args = lapp
[[
  Various flags and option types
    -t (string)   xAPBSC Target
    -s (onoff)    xAPBSC State
    -x            xAPBSC Text
    -l            xAPBSC Level
]]
require("xap")

local cmd = string.format([[
xap-header
{
class=xAPBSC.cmd
target=%s
}
output.state.1
{
id=*
state=%s
]],args.t, args.s)

if args.x then
  cmd = cmd .. "text="..args.x.."\n"
end
if args.l then
  cmd = cmd .. "level="..args.l.."\n"
end
cmd = cmd .. "}"

local ini = config.read("/etc/xap.d/system.ini")
local instance = nil

if ini['xap'] then
   instance = ini.xap['instance']
end
if instance == nil then 
   instance=stringx.split(socket.dns.gethostname(),'.')[1] 
end

xap.init{instance="bscmsg",uid="FF00DF00"}
xap.sendShort(cmd)
