#!/bin/sh

. /etc/ini.conf

ftppid() {
  pid=$(ps | fgrep -v awk | awk '/ftpd/ {print $1}')
}

case "$1" in
    start)
	if [ `iniget $INI network ftp_enable 0` -eq 1 ]; then
                ftppid	    
		if [ -z "$pid" ]; then
	    		tcpsvd -vE 0.0.0.0 21 ftpd -w / &
		fi
	fi
        ;;
    stop)
        ftppid	    
        kill $pid 2>/dev/null
        ;;
    restart)
	$0 stop
	$0 start
	;;
    status)
        ftppid	    
        if [ -n "$pid" ]; then
		echo "running"
	else
		echo "stopped"
        fi
        ;;
esac
