#!/bin/ash

case "$1" in
    start)
        inetd 
        ;;
    stop)
        killall inetd 2>/dev/null
        ;;
    restart)
	$0 stop
	$0 start
	;;
    status)
        if pidof inetd | sed "s/$$\$//" | grep -q [0-9] ; then
	    echo "running"
        else
	    echo "stopped"
        fi
        ;;
esac
