#!/bin/sh

. /etc/ini.conf

case "$1" in
    start)
	if [ `iniget $INI hardware power 1` -eq 1 ]; then
		/bin/ledctrl Power On
	else
		/bin/ledctrl Power Off
	fi
        ;;
    stop)
        ;;
    restart)
	$0 start
	;;
esac
