#!/bin/sh

INI="/etc/xap.d/system.ini"
# Strange?  Try fallback.
if [ ! -f $INI ]; then
   INI = "/etc/xap-livebox.ini"
fi

case "$1" in
    start)
	
	if [ `iniget $INI network ssh_enable 1` -eq 1 ]; then
		if ! pidof dropbear >/dev/null ; then
		        port=`iniget $INI network ssh_port 22`
	    		dropbear -p $port
		fi
	fi
        ;;
    stop)
        killall dropbear 2>/dev/null
        ;;
    restart)
	$0 stop
	$0 start
	;;
    status)
        if pidof dropbear >/dev/null ; then
		echo "running"
	else
		echo "stopped"
        fi
        ;;
    *)	
	echo "Usage: $0 start|stop|restart|status"
	;;
esac
