#!/bin/sh

INI="/etc/xap.d/system.ini"
# Strange?  Try fallback.
if [ ! -f $INI ]; then
   INI = "/etc/xap-livebox.ini"
fi

case "$1" in
    start)
	if [ `iniget $INI network telnet_enable 0` -eq 1 ]; then
		if ! pidof telnetd >/dev/null ; then
		        port=`iniget $INI network telnet_port 23`
	    		telnetd -p $port
		fi
	fi
        ;;
    stop)
        killall telnetd 2>/dev/null
        ;;
    restart)
	$0 stop
	$0 start
	;;
    status)
        if pidof telnetd >/dev/null; then
		echo "running"
	else
		echo "stopped"
        fi
        ;;
    *)	
	echo "Usage: $0 start|stop|restart|status"
	;;
esac
