#!/bin/sh
#
# /etc/init.d/xap start [component...]
# /etc/init.d/xap stop [component...]

. /etc/ini.conf

subsystem="hub pachube livebox web sms currentcost twitter googlecal bridge serial plugboard"

start_web() {
    rm -f /tmp/klone_sess*
    /usr/bin/kloned    
}

stop_web() {
    killall kloned
}

start_hub() {
    /usr/bin/xap-hub -i $MYDEV &
}

stop_hub() {
    killall xap-hub
}

start_livebox() {
    /usr/bin/xap-livebox -s /dev/ttyS0 -i $MYDEV &
}
stop_livebox() {
    killall xap-livebox
}

start_serial() {
    if [ `iniget $INI serial enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-serial -i $MYDEV &
    fi
}
stop_serial() {
    killall xap-serial
}

start_twitter() {
    if [ `iniget $INI twitter enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-twitter -i $MYDEV &
    fi
}
stop_twitter() {
    killall xap-twitter
}

start_sms() {
    if [ `iniget $INI sms enable 0` -eq 1 ] ;  then 
	USBSERIAL=`iniget $INI sms usbserial /dev/ttyUSB0`
	/usr/bin/xap-sms -s $USBSERIAL -i $MYDEV &
    fi
}
stop_sms() {
    killall xap-sms
}

start_pachube() {
    if [ `iniget $INI pachube enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-pachube -i $MYDEV &
    fi
}
stop_pachube() {
    killall xap-pachube
}

start_currentcost() {
    if [ `iniget $INI currentcost enable 0` -eq 1 ] ;  then 
	USBSERIAL=`iniget $INI currentcost usbserial /dev/ttyUSB0`
	/usr/bin/xap-currentcost -s $USBSERIAL -i $MYDEV &
    fi
}
stop_currentcost() {
    killall xap-currentcost
}

start_googlecal() {
    if [ `iniget $INI googlecal enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-googlecal -i $MYDEV &
    fi
}
stop_googlecal() {
    killall xap-googlecal
}

start_plugboard() {
    if [ `iniget $INI plugboard enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-plugboard -i $MYDEV &
    fi
}
stop_plugboard() {
    killall xap-plugboard
}

start_bridge() {
    if [ `iniget $INI bridge enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-bridge -i $MYDEV &
    fi
}
stop_bridge() {
    killall xap-bridge
}

# Param 1: subsystem
all() {
    local i cmd
    IFS=" "
    for i in $subsystem; do
	cmd="$1_$i"
	$cmd 2>/dev/null
   	if [ "$1" = "start" ]; then
     		sleep 1
   	fi
    done
}

# Param 1: [start|stop]
# Param 2: subsystem
subsystem() {
    local i cmd
    IFS=" "
    for i in $subsystem; do
	if [ "$i" = "$2" ]; then
	    cmd="$1_$2"
	    $cmd 2>/dev/null
	    return
	fi
    done
    echo "Subsystem $2 not found"
}

if [ `iniget $INI network config_bridge 1` -eq 0 ] ;  then 
    MYDEV=eth0
else
    MYDEV=br0	
fi

case $1 in
    start|stop)
	if [ -z "$2" ]; then
	    all $1
	else
	    action=$1
	    shift
	    for i in $*; do
	      subsystem $action $i
            done
	fi
	;;
    restart)
	if [ -z "$2" ]; then
	    all stop
	    all start
	else
	    shift
	    for i in $*; do
	      subsystem stop $i
	      subsystem start $i
            done
	fi
	;;
     
    *)
	echo "Usage $0 <start|stop|restart> [component...]"
esac
