#!/bin/sh
#
# /etc/init.d/xap start [component...]
# /etc/init.d/xap stop [component...]

subsystem="hub xively livebox iserver web sms serial currentcost twitter googlecal plugboard urfrx"

start_web() {
    rm -f /tmp/klone_sess*
    if [ -f /etc/kloned.conf ]; then
	/usr/bin/kloned -f /etc/kloned.conf
    else
	/usr/bin/kloned
    fi
}

stop_web() {
    killall kloned
}

start_hub() {
    /usr/bin/xap-hub -i $MYDEV > /var/log/xap-hub.log 2>&1 &
    sleep 1
}

stop_hub() {
    killall xap-hub
}

start_livebox() {
    /usr/bin/xap-livebox -s /dev/ttyS0 -i $MYDEV >/var/log/xap-livebox.log 2>&1 &
}
stop_livebox() {
    killall xap-livebox
}

start_serial() {
    INI="/etc/xap.d/xap-serial.ini"
    if [ `iniget $INI serial enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-serial -i $MYDEV >/var/log/xap-serial.log 2>&1 &
    fi
}
stop_serial() {
    killall xap-serial
}

start_twitter() {
    INI="/etc/xap.d/xap-twitter.ini"
    if [ `iniget $INI twitter enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-twitter -i $MYDEV >/var/log/xap-twitter.log 2>&1 &
    fi
}
stop_twitter() {
    killall xap-twitter
}

start_sms() {
    INI="/etc/xap.d/xap-sms.ini"
    if [ `iniget $INI sms enable 0` -eq 1 ] ;  then 
	USBSERIAL=`iniget $INI sms usbserial /dev/ttyUSB0`
	/usr/bin/xap-sms -s $USBSERIAL -i $MYDEV >/var/log/xap-sms.log 2>&1 &
    fi
}
stop_sms() {
    killall xap-sms
}

start_xively() {
    INI="/etc/xap.d/xap-xively.ini"
    if [ `iniget $INI xively enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-xively -i $MYDEV >/var/log/xap-xively.log 2>&1 &
    fi
}
stop_xively() {
    killall xap-xively
}

start_currentcost() {
    INI="/etc/xap.d/xap-currentcost.ini"
    if [ `iniget $INI currentcost enable 0` -eq 1 ] ;  then 
	USBSERIAL=`iniget $INI currentcost usbserial /dev/ttyUSB0`
	/usr/bin/xap-currentcost -s $USBSERIAL -i $MYDEV >/var/log/xap-currentcost.log 2>&1 &
    fi
}
stop_currentcost() {
    killall xap-currentcost
}

start_googlecal() {
    INI="/etc/xap.d/xap-googlecal.ini"
    if [ `iniget $INI googlecal enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-googlecal -i $MYDEV >/var/log/xap-googlecal.log 2>&1 &
    fi
}
stop_googlecal() {
    killall xap-googlecal
}

start_plugboard() {
    INI="/etc/xap.d/plugboad.ini"
    if [ `iniget $INI plugboard enable 0` -eq 1 ] ;  then 
	/usr/bin/xap-plugboard >/var/log/xap-plugboard.log 2>&1 &
	pid=$!
	echo $pid >/var/run/xap-plugboard.pid
    fi
}

stop_plugboard() {
    kill `cat /var/run/xap-plugboard.pid`
}

start_iserver() {
    INI="/etc/xap.d/iserver.ini"
    if [ `iniget $INI iserver enable 0` -eq 1 ] ;  then 
	/usr/bin/iServer -i $MYDEV >/var/log/iserver.log 2>&1 &
    fi
}
stop_iserver() {
    killall iServer
}

start_urfrx() {
    INI="/etc/xap.d/xap-urfrx.ini"
    if [ `iniget $INI urfrx enable 0` -eq 1 ] ;  then 
	SERIALPORT=`iniget $INI urfrx serialport /dev/ttyUSB0`
	/usr/bin/xap-urfrx -i $MYDEV -s $SERIALPORT >/var/log/xap-urfrx.log 2>&1 &
    fi
}
stop_urfrx() {
    killall xap-urfrx
}

# Param 1: subsystem
all() {
    local i cmd
    IFS=" "
    for i in $subsystem; do
	cmd="$1_$i"
	$cmd 2>/dev/null
    done
}

# Param 1: [start|stop]
# Param 2: subsystem
subsystem() {
    local i cmd
    IFS=" "
    for i in $subsystem; do
	if [ "$i" = "$2" ]; then
	    cmd="$1_$2"
	    $cmd 2>/dev/null
	    return
	fi
    done
    echo "Subsystem $2 not found"
}

INI="/etc/xap.d/system.ini"
if [ `iniget $INI network config_bridge 1` -eq 0 ] ;  then 
    MYDEV=eth0
else
    MYDEV=br0	
fi

case $1 in
    start|stop)
	if [ -z "$2" ]; then
	    all $1
	else
	    action=$1
	    shift
	    for i in $*; do
	      subsystem $action $i
            done
	fi
	;;
    restart)
	if [ -z "$2" ]; then
	    all stop
	    all start
	else
	    shift
	    for i in $*; do
	      subsystem stop $i
	      subsystem start $i
            done
	fi
	;;
     
    *)
	echo "Usage $0 <start|stop|restart> [component...]"
esac
